/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatRequest = IDL.Record({ 'message' : IDL.Text });
export const ChatResponse = IDL.Record({
  'message' : IDL.Text,
  'response' : IDL.Text,
});
export const ScheduleEventId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ActivityStats = IDL.Record({
  'unreadNotifications' : IDL.Nat,
  'memoryEntries' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'completedReminders' : IDL.Nat,
  'pendingReminders' : IDL.Nat,
});
export const MemoryEntry = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Timestamp,
});
export const IntegrationStatus = IDL.Record({
  'files' : IDL.Bool,
  'contacts' : IDL.Bool,
  'messages' : IDL.Bool,
  'email' : IDL.Bool,
  'calendar' : IDL.Bool,
  'camera' : IDL.Bool,
});
export const NotificationSource = IDL.Variant({
  'email' : IDL.Null,
  'calendar' : IDL.Null,
  'message' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'source' : NotificationSource,
  'suggestion' : IDL.Text,
  'dismissed' : IDL.Bool,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'note' : IDL.Text,
  'completed' : IDL.Bool,
  'dueTime' : Timestamp,
});
export const ScheduleEvent = IDL.Record({
  'id' : ScheduleEventId,
  'startTime' : Timestamp,
  'title' : IDL.Text,
  'endTime' : Timestamp,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'completed' : IDL.Bool,
  'category' : IDL.Text,
});
export const ChatTone = IDL.Variant({
  'humorous' : IDL.Null,
  'friendly' : IDL.Null,
  'casual' : IDL.Null,
  'formal' : IDL.Null,
});
export const AssistantSettings = IDL.Record({
  'notificationsEnabled' : IDL.Bool,
  'memoryTrackingEnabled' : IDL.Bool,
  'tone' : ChatTone,
  'assistantDisplayName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
  'clearChatHistory' : IDL.Func([], [], []),
  'completeReminder' : IDL.Func([IDL.Nat], [], []),
  'completeScheduleEvent' : IDL.Func([ScheduleEventId], [IDL.Bool], []),
  'createReminder' : IDL.Func([IDL.Text, IDL.Text, Timestamp], [IDL.Nat], []),
  'createScheduleEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Timestamp, Timestamp, IDL.Text],
      [ScheduleEventId],
      [],
    ),
  'deleteMemoryEntry' : IDL.Func([IDL.Text], [], []),
  'deleteReminder' : IDL.Func([IDL.Nat], [], []),
  'deleteScheduleEvent' : IDL.Func([ScheduleEventId], [IDL.Bool], []),
  'dismissNotification' : IDL.Func([IDL.Nat], [], []),
  'getActivityStats' : IDL.Func([], [ActivityStats], ['query']),
  'getAllMemoryEntries' : IDL.Func([], [IDL.Vec(MemoryEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getIntegrationStatus' : IDL.Func([], [IntegrationStatus], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getScheduleEvents' : IDL.Func([], [IDL.Vec(ScheduleEvent)], ['query']),
  'getScheduleEventsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScheduleEvent)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [AssistantSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedMockNotifications' : IDL.Func([], [], []),
  'setIntegrationStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateMemoryEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateScheduleEvent' : IDL.Func(
      [
        ScheduleEventId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Timestamp,
        Timestamp,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateSettings' : IDL.Func([AssistantSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatRequest = IDL.Record({ 'message' : IDL.Text });
  const ChatResponse = IDL.Record({
    'message' : IDL.Text,
    'response' : IDL.Text,
  });
  const ScheduleEventId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ActivityStats = IDL.Record({
    'unreadNotifications' : IDL.Nat,
    'memoryEntries' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'completedReminders' : IDL.Nat,
    'pendingReminders' : IDL.Nat,
  });
  const MemoryEntry = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const IntegrationStatus = IDL.Record({
    'files' : IDL.Bool,
    'contacts' : IDL.Bool,
    'messages' : IDL.Bool,
    'email' : IDL.Bool,
    'calendar' : IDL.Bool,
    'camera' : IDL.Bool,
  });
  const NotificationSource = IDL.Variant({
    'email' : IDL.Null,
    'calendar' : IDL.Null,
    'message' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'source' : NotificationSource,
    'suggestion' : IDL.Text,
    'dismissed' : IDL.Bool,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'note' : IDL.Text,
    'completed' : IDL.Bool,
    'dueTime' : Timestamp,
  });
  const ScheduleEvent = IDL.Record({
    'id' : ScheduleEventId,
    'startTime' : Timestamp,
    'title' : IDL.Text,
    'endTime' : Timestamp,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'completed' : IDL.Bool,
    'category' : IDL.Text,
  });
  const ChatTone = IDL.Variant({
    'humorous' : IDL.Null,
    'friendly' : IDL.Null,
    'casual' : IDL.Null,
    'formal' : IDL.Null,
  });
  const AssistantSettings = IDL.Record({
    'notificationsEnabled' : IDL.Bool,
    'memoryTrackingEnabled' : IDL.Bool,
    'tone' : ChatTone,
    'assistantDisplayName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
    'clearChatHistory' : IDL.Func([], [], []),
    'completeReminder' : IDL.Func([IDL.Nat], [], []),
    'completeScheduleEvent' : IDL.Func([ScheduleEventId], [IDL.Bool], []),
    'createReminder' : IDL.Func([IDL.Text, IDL.Text, Timestamp], [IDL.Nat], []),
    'createScheduleEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Timestamp, Timestamp, IDL.Text],
        [ScheduleEventId],
        [],
      ),
    'deleteMemoryEntry' : IDL.Func([IDL.Text], [], []),
    'deleteReminder' : IDL.Func([IDL.Nat], [], []),
    'deleteScheduleEvent' : IDL.Func([ScheduleEventId], [IDL.Bool], []),
    'dismissNotification' : IDL.Func([IDL.Nat], [], []),
    'getActivityStats' : IDL.Func([], [ActivityStats], ['query']),
    'getAllMemoryEntries' : IDL.Func([], [IDL.Vec(MemoryEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getIntegrationStatus' : IDL.Func([], [IntegrationStatus], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getScheduleEvents' : IDL.Func([], [IDL.Vec(ScheduleEvent)], ['query']),
    'getScheduleEventsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScheduleEvent)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [AssistantSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedMockNotifications' : IDL.Func([], [], []),
    'setIntegrationStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateMemoryEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateScheduleEvent' : IDL.Func(
        [
          ScheduleEventId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Timestamp,
          Timestamp,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateSettings' : IDL.Func([AssistantSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };