/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ActivityStats {
    unreadNotifications: bigint;
    memoryEntries: bigint;
    totalMessages: bigint;
    completedReminders: bigint;
    pendingReminders: bigint;
}
export type Timestamp = bigint;
export interface MemoryEntry {
    key: string;
    value: string;
}
export interface ScheduleEvent {
    id: ScheduleEventId;
    startTime: Timestamp;
    title: string;
    endTime: Timestamp;
    date: string;
    note: string;
    completed: boolean;
    category: string;
}
export interface AssistantSettings {
    notificationsEnabled: boolean;
    memoryTrackingEnabled: boolean;
    tone: ChatTone;
    assistantDisplayName: string;
}
export interface Reminder {
    id: bigint;
    title: string;
    note: string;
    completed: boolean;
    dueTime: Timestamp;
}
export interface ChatRequest {
    message: string;
}
export type ScheduleEventId = bigint;
export interface Notification {
    id: bigint;
    content: string;
    source: NotificationSource;
    suggestion: string;
    dismissed: boolean;
}
export interface Message {
    content: string;
    role: string;
    timestamp: Timestamp;
}
export interface IntegrationStatus {
    files: boolean;
    contacts: boolean;
    messages: boolean;
    email: boolean;
    calendar: boolean;
    camera: boolean;
}
export interface ChatResponse {
    message: string;
    response: string;
}
export interface UserProfile {
    username: string;
    email: string;
}
export enum ChatTone {
    humorous = "humorous",
    friendly = "friendly",
    casual = "casual",
    formal = "formal"
}
export enum NotificationSource {
    email = "email",
    calendar = "calendar",
    message = "message"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    chat(request: ChatRequest): Promise<ChatResponse>;
    clearChatHistory(): Promise<void>;
    completeReminder(id: bigint): Promise<void>;
    completeScheduleEvent(id: ScheduleEventId): Promise<boolean>;
    createReminder(title: string, note: string, dueTime: Timestamp): Promise<bigint>;
    createScheduleEvent(title: string, note: string, category: string, startTime: Timestamp, endTime: Timestamp, date: string): Promise<ScheduleEventId>;
    deleteMemoryEntry(key: string): Promise<void>;
    deleteReminder(id: bigint): Promise<void>;
    deleteScheduleEvent(id: ScheduleEventId): Promise<boolean>;
    dismissNotification(id: bigint): Promise<void>;
    getActivityStats(): Promise<ActivityStats>;
    getAllMemoryEntries(): Promise<Array<MemoryEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatHistory(): Promise<Array<Message>>;
    getIntegrationStatus(): Promise<IntegrationStatus>;
    getNotifications(): Promise<Array<Notification>>;
    getReminders(): Promise<Array<Reminder>>;
    getScheduleEvents(): Promise<Array<ScheduleEvent>>;
    getScheduleEventsByDate(date: string): Promise<Array<ScheduleEvent>>;
    getSettings(): Promise<AssistantSettings>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedMockNotifications(): Promise<void>;
    setIntegrationStatus(integration: string, enabled: boolean): Promise<void>;
    updateMemoryEntry(key: string, value: string): Promise<void>;
    updateScheduleEvent(id: ScheduleEventId, title: string, note: string, category: string, startTime: Timestamp, endTime: Timestamp, date: string): Promise<boolean>;
    updateSettings(newSettings: AssistantSettings): Promise<void>;
}
import type { AssistantSettings as _AssistantSettings, ChatTone as _ChatTone, Notification as _Notification, NotificationSource as _NotificationSource, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async chat(arg0: ChatRequest): Promise<ChatResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.chat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chat(arg0);
            return result;
        }
    }
    async clearChatHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatHistory();
            return result;
        }
    }
    async completeReminder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeReminder(arg0);
            return result;
        }
    }
    async completeScheduleEvent(arg0: ScheduleEventId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeScheduleEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeScheduleEvent(arg0);
            return result;
        }
    }
    async createReminder(arg0: string, arg1: string, arg2: Timestamp): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(arg0, arg1, arg2);
            return result;
        }
    }
    async createScheduleEvent(arg0: string, arg1: string, arg2: string, arg3: Timestamp, arg4: Timestamp, arg5: string): Promise<ScheduleEventId> {
        if (this.processError) {
            try {
                const result = await this.actor.createScheduleEvent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScheduleEvent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteMemoryEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMemoryEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMemoryEntry(arg0);
            return result;
        }
    }
    async deleteReminder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async deleteScheduleEvent(arg0: ScheduleEventId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheduleEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheduleEvent(arg0);
            return result;
        }
    }
    async dismissNotification(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissNotification(arg0);
            return result;
        }
    }
    async getActivityStats(): Promise<ActivityStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityStats();
            return result;
        }
    }
    async getAllMemoryEntries(): Promise<Array<MemoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemoryEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemoryEntries();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatHistory(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return result;
        }
    }
    async getIntegrationStatus(): Promise<IntegrationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntegrationStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntegrationStatus();
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminders();
            return result;
        }
    }
    async getScheduleEvents(): Promise<Array<ScheduleEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduleEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduleEvents();
            return result;
        }
    }
    async getScheduleEventsByDate(arg0: string): Promise<Array<ScheduleEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduleEventsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduleEventsByDate(arg0);
            return result;
        }
    }
    async getSettings(): Promise<AssistantSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_AssistantSettings_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_AssistantSettings_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedMockNotifications(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedMockNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedMockNotifications();
            return result;
        }
    }
    async setIntegrationStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setIntegrationStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setIntegrationStatus(arg0, arg1);
            return result;
        }
    }
    async updateMemoryEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemoryEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemoryEntry(arg0, arg1);
            return result;
        }
    }
    async updateScheduleEvent(arg0: ScheduleEventId, arg1: string, arg2: string, arg3: string, arg4: Timestamp, arg5: Timestamp, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScheduleEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScheduleEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateSettings(arg0: AssistantSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_AssistantSettings_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_AssistantSettings_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AssistantSettings_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssistantSettings): AssistantSettings {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ChatTone_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatTone): ChatTone {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationSource_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationSource): NotificationSource {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationsEnabled: boolean;
    memoryTrackingEnabled: boolean;
    tone: _ChatTone;
    assistantDisplayName: string;
}): {
    notificationsEnabled: boolean;
    memoryTrackingEnabled: boolean;
    tone: ChatTone;
    assistantDisplayName: string;
} {
    return {
        notificationsEnabled: value.notificationsEnabled,
        memoryTrackingEnabled: value.memoryTrackingEnabled,
        tone: from_candid_ChatTone_n13(_uploadFile, _downloadFile, value.tone),
        assistantDisplayName: value.assistantDisplayName
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    source: _NotificationSource;
    suggestion: string;
    dismissed: boolean;
}): {
    id: bigint;
    content: string;
    source: NotificationSource;
    suggestion: string;
    dismissed: boolean;
} {
    return {
        id: value.id,
        content: value.content,
        source: from_candid_NotificationSource_n9(_uploadFile, _downloadFile, value.source),
        suggestion: value.suggestion,
        dismissed: value.dismissed
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email: null;
} | {
    calendar: null;
} | {
    message: null;
}): NotificationSource {
    return "email" in value ? NotificationSource.email : "calendar" in value ? NotificationSource.calendar : "message" in value ? NotificationSource.message : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    humorous: null;
} | {
    friendly: null;
} | {
    casual: null;
} | {
    formal: null;
}): ChatTone {
    return "humorous" in value ? ChatTone.humorous : "friendly" in value ? ChatTone.friendly : "casual" in value ? ChatTone.casual : "formal" in value ? ChatTone.formal : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n7(_uploadFile, _downloadFile, x));
}
function to_candid_AssistantSettings_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssistantSettings): _AssistantSettings {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ChatTone_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatTone): _ChatTone {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationsEnabled: boolean;
    memoryTrackingEnabled: boolean;
    tone: ChatTone;
    assistantDisplayName: string;
}): {
    notificationsEnabled: boolean;
    memoryTrackingEnabled: boolean;
    tone: _ChatTone;
    assistantDisplayName: string;
} {
    return {
        notificationsEnabled: value.notificationsEnabled,
        memoryTrackingEnabled: value.memoryTrackingEnabled,
        tone: to_candid_ChatTone_n17(_uploadFile, _downloadFile, value.tone),
        assistantDisplayName: value.assistantDisplayName
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatTone): {
    humorous: null;
} | {
    friendly: null;
} | {
    casual: null;
} | {
    formal: null;
} {
    return value == ChatTone.humorous ? {
        humorous: null
    } : value == ChatTone.friendly ? {
        friendly: null
    } : value == ChatTone.casual ? {
        casual: null
    } : value == ChatTone.formal ? {
        formal: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
